import stp

let text = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultricies mi quis hendrerit dolor. Amet nulla facilisi morbi tempus. Quis ipsum suspendisse ultrices gravida. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Orci a scelerisque purus semper eget duis at tellus. Proin sed libero enim sed. Massa sed elementum tempus egestas. Eu non diam phasellus vestibulum. Sed cras ornare arcu dui vivamus. Quis blandit turpis cursus in hac habitasse. Diam in arcu cursus euismod quis viverra nibh cras. Ut aliquam purus sit amet luctus. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Pretium viverra suspendisse potenti nullam. Vehicula ipsum a arcu cursus. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Tincidunt arcu non sodales neque sodales ut etiam.

Nunc faucibus a pellentesque sit amet porttitor eget dolor.

Adipiscing commodo elit at imperdiet dui.

Arcu risus quis varius quam quisque id diam.

Erat pellentesque adipiscing commodo elit at imperdiet dui.

Proin sed libero enim sed faucibus turpis in eu mi.

Elit ullamcorper dignissim cras tincidunt.

Montes nascetur ridiculus mus mauris.

Sit amet commodo nulla facilisi nullam.

Id leo in vitae turpis massa sed.

Massa id neque aliquam vestibulum.

Lacus vel facilisis volutpat est velit egestas dui id ornare.

Vel orci porta non pulvinar neque laoreet suspendisse interdum.

Neque aliquam vestibulum morbi blandit cursus risus at. Mi ipsum faucibus vitae aliquet nec. Nam libero justo laoreet sit amet cursus sit amet. Mauris in aliquam sem fringilla ut morbi. Faucibus nisl tincidunt eget nullam non nisi est sit amet. A diam sollicitudin tempor id. Non nisi est sit amet facilisis magna etiam tempor orci. Magna sit amet purus gravida quis. Aliquet nec ullamcorper sit amet risus. At auctor urna nunc id cursus metus. Neque gravida in fermentum et sollicitudin ac orci. Justo eget magna fermentum iaculis eu non. Quis lectus nulla at volutpat diam ut. Ultrices dui sapien eget mi. Orci sagittis eu volutpat odio facilisis mauris sit amet massa. Viverra vitae congue eu consequat ac felis donec et. Fringilla urna porttitor rhoncus dolor purus non enim praesent.

In est ante in nibh mauris cursus mattis molestie a. Arcu non sodales neque sodales ut etiam. Mattis enim ut tellus elementum sagittis vitae et leo. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Egestas sed sed risus pretium. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Neque laoreet suspendisse interdum consectetur libero id faucibus. Dictum non consectetur a erat nam. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Ac tincidunt vitae semper quis lectus nulla. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel. Sagittis nisl rhoncus mattis rhoncus. Eget gravida cum sociis natoque penatibus et. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur.

Vel pretium lectus quam id leo. Turpis massa sed elementum tempus egestas sed sed. Enim blandit volutpat maecenas volutpat. Viverra nam libero justo laoreet. Porttitor lacus luctus accumsan tortor posuere ac ut. Sagittis vitae et leo duis ut diam quam nulla porttitor. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Augue eget arcu dictum varius duis at consectetur. Tortor pretium viverra suspendisse potenti nullam ac. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Diam sollicitudin tempor id eu nisl. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Ornare massa eget egestas purus. Id neque aliquam vestibulum morbi blandit cursus risus at. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Ut tellus elementum sagittis vitae. At quis risus sed vulputate odio ut enim blandit volutpat.

Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Pharetra magna ac placerat vestibulum. Turpis cursus in hac habitasse platea. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Diam vulputate ut pharetra sit amet aliquam id. Tincidunt eget nullam non nisi est sit amet facilisis magna. Ut venenatis tellus in metus. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Nec dui nunc mattis enim. Nulla at volutpat diam ut. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Integer quis auctor elit sed vulputate mi sit.

Id consectetur purus ut faucibus pulvinar elementum integer enim. Venenatis tellus in metus vulputate. Vitae tempus quam pellentesque nec nam aliquam sem et. Amet purus gravida quis blandit turpis cursus in hac habitasse. Fermentum odio eu feugiat pretium nibh ipsum. Euismod lacinia at quis risus. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Duis ultricies lacus sed turpis tincidunt. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Augue ut lectus arcu bibendum at varius vel pharetra vel. Interdum posuere lorem ipsum dolor sit amet. Congue nisi vitae suscipit tellus mauris a. Quis eleifend quam adipiscing vitae proin sagittis nisl. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Tempus urna et pharetra pharetra massa. Tellus cras adipiscing enim eu turpis egestas pretium aenean.

Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Lorem ipsum dolor sit amet consectetur adipiscing elit. Ut tristique et egestas quis ipsum. In pellentesque massa placerat duis ultricies lacus sed. Feugiat vivamus at augue eget arcu dictum varius. Nam libero justo laoreet sit amet cursus. Fringilla phasellus faucibus scelerisque eleifend. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Mauris augue neque gravida in. Et malesuada fames ac turpis egestas integer eget. Tincidunt vitae semper quis lectus nulla at. Fames ac turpis egestas sed tempus urna et. Risus sed vulputate odio ut enim blandit volutpat. Luctus venenatis lectus magna fringilla urna porttitor. Nisl nunc mi ipsum faucibus vitae. Curabitur vitae nunc sed velit.

Duis tristique sollicitudin nibh sit. Consequat nisl vel pretium lectus quam. Amet porttitor eget dolor morbi non arcu risus quis varius. Elementum facilisis leo vel fringilla est. Feugiat in fermentum posuere urna nec tincidunt praesent. Eget lorem dolor sed viverra. Consectetur adipiscing elit pellentesque habitant. Tortor dignissim convallis aenean et. Suspendisse faucibus interdum posuere lorem ipsum dolor sit. Sagittis eu volutpat odio facilisis mauris sit amet massa vitae. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Volutpat diam ut venenatis tellus in. Eget dolor morbi non arcu risus quis varius quam. Sit amet dictum sit amet. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Faucibus scelerisque eleifend donec pretium vulputate sapien. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Vestibulum sed arcu non odio euismod lacinia at quis risus. Velit dignissim sodales ut eu sem integer vitae justo.

Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Eget nunc lobortis mattis aliquam faucibus purus in massa tempor. Egestas maecenas pharetra convallis posuere morbi leo. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Commodo nulla facilisi nullam vehicula ipsum a. Maecenas ultricies mi eget mauris. Lorem dolor sed viverra ipsum nunc. Faucibus pulvinar elementum integer enim. Vitae nunc sed velit dignissim sodales ut eu sem integer.

Sed risus pretium quam vulputate dignissim suspendisse in. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Ut tellus elementum sagittis vitae et leo duis ut. Id porta nibh venenatis cras sed felis. Et malesuada fames ac turpis egestas maecenas pharetra convallis. Sapien eget mi proin sed libero enim. Dui faucibus in ornare quam viverra orci. Lacus viverra vitae congue eu consequat ac. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Nunc sed augue lacus viverra vitae congue eu consequat ac. Faucibus a pellentesque sit amet. Sed vulputate mi sit amet mauris commodo. Suscipit adipiscing bibendum est ultricies. In fermentum et sollicitudin ac.

Sit amet mattis vulputate enim. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Et netus et malesuada fames ac turpis egestas sed tempus. Enim nec dui nunc mattis enim ut tellus. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Egestas congue quisque egestas diam. Commodo elit at imperdiet dui. Risus quis varius quam quisque id diam vel quam. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Faucibus ornare suspendisse sed nisi. Faucibus vitae aliquet nec ullamcorper. In egestas erat imperdiet sed euismod. Eu facilisis sed odio morbi quis commodo. Pretium nibh ipsum consequat nisl. Euismod in pellentesque massa placerat duis ultricies lacus sed.

Elementum integer enim neque volutpat ac tincidunt. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Nisl suscipit adipiscing bibendum est ultricies integer. Tellus in hac habitasse platea dictumst vestibulum. Sed risus ultricies tristique nulla aliquet. Fames ac turpis egestas integer eget aliquet. Volutpat ac tincidunt vitae semper quis lectus. Pharetra massa massa ultricies mi quis. Porttitor lacus luctus accumsan tortor posuere ac ut. Iaculis at erat pellentesque adipiscing commodo elit. Urna et pharetra pharetra massa massa. Enim sed faucibus turpis in eu. Lectus magna fringilla urna porttitor rhoncus. Ullamcorper malesuada proin libero nunc consequat interdum varius. Imperdiet massa tincidunt nunc pulvinar. Sit amet commodo nulla facilisi nullam. Neque volutpat ac tincidunt vitae semper quis lectus. Vel fringilla est ullamcorper eget nulla facilisi. Velit scelerisque in dictum non consectetur a.

Vestibulum morbi blandit cursus risus. Dapibus ultrices in iaculis nunc sed augue lacus. Porttitor leo a diam sollicitudin. Leo vel fringilla est ullamcorper eget nulla. Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. In dictum non consectetur a. Cras pulvinar mattis nunc sed blandit libero. Dictum varius duis at consectetur. Ac orci phasellus egestas tellus rutrum. Tortor dignissim convallis aenean et tortor at risus viverra. Urna cursus eget nunc scelerisque viverra mauris. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Purus non enim praesent elementum facilisis leo vel fringilla est. Vel quam elementum pulvinar etiam. Non odio euismod lacinia at quis risus sed vulputate. Mauris nunc congue nisi vitae. Imperdiet proin fermentum leo vel orci. Adipiscing at in tellus integer feugiat scelerisque varius morbi.

Fermentum odio eu feugiat pretium. Ut pharetra sit amet aliquam id diam maecenas ultricies. Vel quam elementum pulvinar etiam non quam lacus suspendisse. Non nisi est sit amet facilisis magna etiam. Pharetra pharetra massa massa ultricies mi quis. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Nunc aliquet bibendum enim facilisis gravida. Diam quis enim lobortis scelerisque. Varius duis at consectetur lorem. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Nunc id cursus metus aliquam eleifend. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Nisl suscipit adipiscing bibendum est ultricies. Lectus sit amet est placerat in egestas erat imperdiet. Ornare lectus sit amet est.

Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Malesuada pellentesque elit eget gravida cum. Convallis a cras semper auctor neque vitae tempus quam. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Lectus sit amet est placerat in egestas erat imperdiet sed. Lacus luctus accumsan tortor posuere ac ut consequat semper. Viverra aliquet eget sit amet tellus. Ipsum a arcu cursus vitae congue. In hendrerit gravida rutrum quisque non. Non diam phasellus vestibulum lorem sed. Orci phasellus egestas tellus rutrum tellus pellentesque. Massa massa ultricies mi quis hendrerit dolor magna eget est. Consequat interdum varius sit amet mattis. Venenatis cras sed felis eget velit aliquet sagittis. Faucibus nisl tincidunt eget nullam non nisi.

Urna porttitor rhoncus dolor purus non. Mauris vitae ultricies leo integer. Auctor eu augue ut lectus arcu bibendum at varius vel. Rutrum quisque non tellus orci ac auctor. Nisi est sit amet facilisis magna etiam. Odio morbi quis commodo odio aenean sed. Leo vel orci porta non pulvinar neque laoreet suspendisse. A pellentesque sit amet porttitor eget dolor. Libero justo laoreet sit amet cursus sit amet dictum. Augue mauris augue neque gravida in fermentum et. Augue eget arcu dictum varius duis at. Venenatis urna cursus eget nunc scelerisque. Etiam sit amet nisl purus in mollis nunc. Purus in mollis nunc sed id. Egestas egestas fringilla phasellus faucibus scelerisque. Ipsum dolor sit amet consectetur adipiscing elit pellentesque. Urna porttitor rhoncus dolor purus non enim praesent. Sed risus pretium quam vulputate. Commodo viverra maecenas accumsan lacus vel facilisis. Nullam ac tortor vitae purus faucibus ornare.

Amet cursus sit amet dictum sit amet. Nec nam aliquam sem et tortor consequat id porta nibh. Pulvinar neque laoreet suspendisse interdum consectetur libero. Leo in vitae turpis massa sed elementum tempus egestas sed. Ut placerat orci nulla pellentesque dignissim enim sit amet. Leo urna molestie at elementum eu. Viverra maecenas accumsan lacus vel facilisis volutpat est. Sed arcu non odio euismod lacinia at quis risus. Fusce ut placerat orci nulla pellentesque. Placerat orci nulla pellentesque dignissim. Non blandit massa enim nec dui nunc mattis enim. Sed risus pretium quam vulputate. Libero nunc consequat interdum varius sit amet mattis. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Quis blandit turpis cursus in hac habitasse platea. Consequat id porta nibh venenatis cras sed.

Quam lacus suspendisse faucibus interdum posuere lorem. Etiam tempor orci eu lobortis elementum nibh tellus molestie nunc. Dui faucibus in ornare quam viverra. Tincidunt arcu non sodales neque sodales ut etiam sit amet. Cursus vitae congue mauris rhoncus aenean vel. Id volutpat lacus laoreet non curabitur gravida arcu. Et netus et malesuada fames ac. Pellentesque habitant morbi tristique senectus. Dignissim sodales ut eu sem integer vitae. Nulla aliquet enim tortor at auctor. Faucibus in ornare quam viverra. Convallis aenean et tortor at risus viverra.

Sed faucibus turpis in eu mi bibendum neque. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae. Tortor vitae purus faucibus ornare suspendisse sed nisi. Hendrerit gravida rutrum quisque non tellus orci ac auctor. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Justo donec enim diam vulputate ut pharetra. Consequat semper viverra nam libero justo. Libero id faucibus nisl tincidunt eget. Dolor sit amet consectetur adipiscing elit ut. Cras fermentum odio eu feugiat pretium nibh. Tempor orci dapibus ultrices in iaculis nunc. Ipsum faucibus vitae aliquet nec. Molestie a iaculis at erat pellentesque adipiscing. Lobortis feugiat vivamus at augue eget arcu dictum. Vestibulum morbi blandit cursus risus. Mauris cursus mattis molestie a iaculis at erat pellentesque. Habitant morbi tristique senectus et. Maecenas sed enim ut sem. Dictum sit amet justo donec enim. Non arcu risus quis varius quam quisque id diam.
"""

STP(text: text)
